apiVersion: v1
entries:
  ad-api:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-06-25T15:25:55.118118+03:00"
    description: Service for rest api for map and telegram bot ui
    digest: 84231bf8c753e8cec1a4ace832fa7618d18fb6106b9ea39d4e675b08734c08da
    name: ad-api
    type: application
    urls:
    - https://raw.githubusercontent.com/sku4/ad-api/refs/heads/master/docs/charts/ad-api-1.0.0.tgz
    version: 1.0.0
generated: "2025-06-25T15:25:55.117228+03:00"
