app:
  street:
    cache_duration: 2h
  map:
    cache_duration: 15m
tarantool:
  servers:
    - "storage.sku:3301"
    - "replica.sku:3301"
  timeout: 10s
  reconnect_interval: 1s
features:
  - "street_id"
  - "house"
  - "price"
  - "price_m2"
  - "rooms"
  - "floor"
  - "year"
  - "m2_main"
telegram:
  timeout: 60
rest:
  port: 8000
  read_timeout: 10s
  write_timeout: 10s
  max_header_bytes: 1048576
template:
  folders:
    - "templates/telegram"
    - "web/telegram"
    - "web/map"
