replicaCount: 1
image:
  repository: ad-api
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred
nameOverride: "ad-api"
fullnameOverride: "ad-api"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  app: ad-api

podSecurityContext: {}
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  create: true
  type: ClusterIP
  externalPort: 80
  internalPort: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ad.gohome.run
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #    - hosts:
  #        - alice.gohome.run
  #      secretName: alice-gohome-run-tls
  email: skubach@tut.by

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

#livenessProbe:
#  httpGet:
#    path: /
#    port: http
#readinessProbe:
#  httpGet:
#    path: /
#    port: http

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate

volumes:
  - name: config
    configMap:
      name: ad-api-config

volumeMounts:
  - name: config
    mountPath: /app/configs

env:
  - name: HOST_URL
    valueFrom:
      secretKeyRef:
        name: ad-app
        key: host_url
  - name: TELEGRAM_BOT_TOKEN
    valueFrom:
      secretKeyRef:
        name: ad-app
        key: telegram_bot_token
  - name: TELEGRAM_FEEDBACK_CHAT_ID
    valueFrom:
      secretKeyRef:
        name: ad-app
        key: telegram_feedback_chat_id

nodeSelector: {}

tolerations: []

affinity: {}

tarantoolServers:
  - ad-tnt-master:3301
  - ad-tnt-replica:3302

initContainers:
  - name: init-tnt-master
    image: busybox:1.28
    command: [ 'sh', '-c', "until nslookup ad-tnt-master.ad-prod.svc.cluster.local; do echo waiting for tnt master; sleep 2; done" ]
  - name: init-tnt-replica
    image: busybox:1.28
    command: [ 'sh', '-c', "until nslookup ad-tnt-replica.ad-prod.svc.cluster.local; do echo waiting for tnt replica; sleep 2; done" ]
