name: ci-cd

on:
  push:
    branches: [ master ]

jobs:
  ad-run:
    uses: sku4/ad-run/.github/workflows/go.yml@master
    secrets: inherit
    with:
      image: ad/api
      service: app-api
      prefix: api
      repository: sku4/ad-api
